name: Custom test
on:
  push:
    branches:
      - staging
      - 'fix/**'
      - 'feature/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: npm ci
      - name: Test Delivery Customization
        working-directory: ./1-node-farm/starter
        run: npm run test

